<ul>
  <li><a href="http://nickthecoder.co.uk/pinkwino/view/Friends+and+Family">friends</a></li>
  <li><a title="foolafriend.co.uk" href="http://foolafriend.co.uk/">faf</a></li>
  <li><a title="haveringHypnotherapy.co.uk" href="http://haveringHypnotherapy.co.uk">hh</a></li>
  <li><a id="umbrellaLink" title="umbrella" href="http://nickthecoder.co.uk/umbrella/">um</a></li>
  <li><a id="stickflickLink" title="stickflick" href="http://stickflick.org/">stickflick</a></li>
  <li><a id="ntcLink" title="nickthecoder.co.uk" href="http://nickthecoder.co.uk">ntc</a></li>
</ul><br/>
<ul>
  <li><a href="http://nickthecoder.co.uk/pinkwino/view/Web+Design">web design</a></li>
  <li><a href="http://nickthecoder.co.uk/pinkwino/view/Contact">contact nick</a></li>
</ul><br/>

